@echo off
set %1 ::___subfolderSelection

echo @echo on> %~dp0\__getActiveRobotVars.bat

::Write some comments to mark file as autogenerated
echo ::Autogenerated through ___loadActiveRobot.bat >> %~dp0\__getActiveRobotVars.bat
echo.>> %~dp0\__getActiveRobotVars.bat

::Write set subfolder
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
echo ::# Set subfolder>> %~dp0\__getActiveRobotVars.bat
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
@echo|set /p="set subfolder=">>%~dp0\__getActiveRobotVars.bat
if %___subfolderSelection%==text    "%~dp0\lib\Xidel\xidel.exe" %~dp0\robotEnv.json --silent --xquery '$json("config")("subfolderSettings")("textFolder")'   >> %~dp0\__getActiveRobotVars.bat
if %___subfolderSelection%==binary  "%~dp0\lib\Xidel\xidel.exe" %~dp0\robotEnv.json --silent --xquery '$json("config")("subfolderSettings")("binaryFolder")' >> %~dp0\__getActiveRobotVars.bat
if %___subfolderSelection%==misc    "%~dp0\lib\Xidel\xidel.exe" %~dp0\robotEnv.json --silent --xquery '$json("config")("subfolderSettings")("miscFolder")'   >> %~dp0\__getActiveRobotVars.bat
echo.>> %~dp0\__getActiveRobotVars.bat

::Write set robotsBaseFolder
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
echo ::# Set robotsBaseFolder>> %~dp0\__getActiveRobotVars.bat
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
@echo|set /p="set robotsBaseFolder=">>%~dp0\__getActiveRobotVars.bat
"%~dp0\lib\Xidel\xidel.exe" %~dp0\robotEnv.json --silent --xquery '$json("config")("robotsBaseFolder")' >> %~dp0\__getActiveRobotVars.bat
echo.>> %~dp0\__getActiveRobotVars.bat

::Write set normalizeSource
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
echo ::# Set normalizeSource>> %~dp0\__getActiveRobotVars.bat
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
@echo|set /p="set normalizeSource=">>%~dp0\__getActiveRobotVars.bat
"%~dp0\lib\Xidel\xidel.exe" %~dp0\robotEnv.json --silent --xquery '$json("config")("normalizeSource")' >> %~dp0\__getActiveRobotVars.bat
echo.>> %~dp0\__getActiveRobotVars.bat

::Write set activeRobot
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
echo ::# Set activeRobot>> %~dp0\__getActiveRobotVars.bat
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
@echo|set /p="set activeRobot=">>%~dp0\__getActiveRobotVars.bat
"%~dp0\lib\Xidel\xidel.exe" %~dp0\robotEnv.json --silent --xquery 'for $robot in $json("robots")() where $robot/name=$json("activeRobot") return $robot/robotFolder' >> %~dp0\__getActiveRobotVars.bat
echo.>> %~dp0\__getActiveRobotVars.bat

::Write set roboIP
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
echo ::# Set IP of Robo>> %~dp0\__getActiveRobotVars.bat
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
@echo|set /p="set roboIP=">>%~dp0\__getActiveRobotVars.bat
"%~dp0\lib\Xidel\xidel.exe" %~dp0\robotEnv.json --silent --xquery 'for $robot in $json("robots")() where $robot/name=$json("activeRobot") return $robot/ip' >> %~dp0\__getActiveRobotVars.bat
echo.>> %~dp0\__getActiveRobotVars.bat

::Write set roboPort
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
echo ::# Set PORT of Robo>> %~dp0\__getActiveRobotVars.bat
echo ::######################################################>> %~dp0\__getActiveRobotVars.bat
@echo|set /p="set roboPort=">>%~dp0\__getActiveRobotVars.bat
"%~dp0\lib\Xidel\xidel.exe" %~dp0\robotEnv.json --silent --xquery 'for $robot in $json("robots")() where $robot/name=$json("activeRobot") return $robot/port' >> %~dp0\__getActiveRobotVars.bat
